const styles = {
  singleColorPalette: {
    height: "50%",
  },
  palette: {
    height: "100vh",
    overflow: "hidden",
    flexDirection: "column",
    // background: "rgba(255,255,255,0)",
  },
  paletteColors: {
    height: "90%",
  },
  colorBox: {
    width: "20%",
    height: "25%",
    margin: "0 auto",
    display: "inline-block",
    position: "relative",
    cursor: "pointer",
    marginBottom: "-3.5px",
  },
  emoji: {
    fontSize: "1.5rem",
    margin: "0 1.1rem",
  },
  goBack: {
    width: "20%",
    height: "50%",
    margin: "0 auto",
    display: "inline-block",
    position: "relative",
    cursor: "pointer",
    marginBottom: "-3.5px",
    opacity: 1,
    backgroundColor: "#000",
    "& a": {
      color: "#fff",
      width: "100px",
      height: "30px",
      position: "absolute",
      display: "inline-block",
      top: "50%",
      left: "50%",
      marginLeft: "-50px",
      marginTop: "-15px",
      textAlign: "center",
      outline: "none",
      background: "rgba(255, 255, 255, 0.3)",
      fontSize: "1rem",
      lineHeight: "30px",
      textTransform: "uppercase",
      border: "none",
      textDecoration: "none",
    },
  },
  // backBtn: {
  //   width: "100px",
  //   height: "30px",
  //   position: "absolute",
  //   display: "inline-block",
  //   top: "50%",
  //   left: "50%",
  //   marginLeft: "-50px",
  //   marginTop: "-15px",
  //   textAlign: "center",
  //   outline: "none",
  //   // background: "rgba(255, 255, 255, 0=)",
  //   fontSize: "1rem",
  //   lineHeight: "30px",
  //   color: "#fff",
  //   textTransform: "uppercase",
  //   border: "none",
  //   textDecoration: "none",
  //   background: "rgba(255, 255, 255, 0.3)",
  //   // position: "relative",
  // },
};

export default styles;
